#!/bin/bash

set -u
set -e

FINANCES_YAML="$(mktemp)"
REVENUE_JSON="../mtlynch.io/static/data/project-finances.json"

for project in "tinypilot" "htfp" "isitketo" "zestful"
do
  CSV_URL_FILE="csv-url-${project}.txt"
  CSV_URL="$(cat $CSV_URL_FILE)"
  RAW_CSV="$(mktemp)"
  wget -qO- "$CSV_URL" > "${RAW_CSV}"

  echo "### ${project}"
  cat "${RAW_CSV}" | ./app/main.py --project="${project}" 2> /dev/null

  cat "${RAW_CSV}" | ./app/main.py --to-yaml --project="${project}" >> "${FINANCES_YAML}" 2> /dev/null
done

yq --output-format json "${FINANCES_YAML}" > "${REVENUE_JSON}"
